"""商品目标模型首期。仅适用于已经明确清空旧商品数据的环境。

Revision ID: 20260922_01
Revises: 20260918_02

DDL 已冻结，不导入运行时 Model。迁移本身不删除数据。
"""

from alembic import op

revision = "20260922_01"
down_revision = "20260918_02"
branch_labels = None
depends_on = None


DDL = (
    "DO $$ BEGIN\nIF EXISTS (SELECT 1 FROM products) OR EXISTS (SELECT 1 FROM inventory_movements)\nTHEN RAISE EXCEPTION 'Catalog migration requires an empty commerce dataset; reset only the explicitly authorized local development database first';\nEND IF;\nEND $$",
    "CREATE TABLE brands (\n\tname VARCHAR(100) NOT NULL, \n\tlogo_asset_id UUID, \n\tdescription TEXT NOT NULL, \n\tsort_order INTEGER, \n\tis_active BOOLEAN NOT NULL, \n\trevision INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_brands_name CHECK (length(btrim(name)) > 0), \n\tCONSTRAINT ck_brands_revision CHECK (revision > 0), \n\tCONSTRAINT ck_brands_sort CHECK (sort_order >= 0), \n\tFOREIGN KEY(logo_asset_id) REFERENCES assets (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_brands_active_sort ON brands (is_active, sort_order, id)",
    "CREATE INDEX ix_brands_logo_asset_id ON brands (logo_asset_id)",
    "COMMENT ON TABLE brands IS '独立品牌资料，停用仅阻止新关联'",
    "COMMENT ON COLUMN brands.name IS '品牌名称'",
    "COMMENT ON COLUMN brands.logo_asset_id IS '品牌图片资产'",
    "COMMENT ON COLUMN brands.description IS '品牌介绍'",
    "COMMENT ON COLUMN brands.sort_order IS '排序权重，值越小越靠前，NULL 表示未人工设置自动排最后'",
    "COMMENT ON COLUMN brands.is_active IS '是否允许新关联'",
    "COMMENT ON COLUMN brands.revision IS '编辑版本'",
    "ALTER TABLE product_categories ADD CONSTRAINT ck_product_category_sort CHECK (sort_order >= 0)",
    "CREATE INDEX ix_product_category_parent_sort ON product_categories (parent_id, sort_order, id)",
    "ALTER TABLE products DROP COLUMN shipping_template_id",
    "DROP INDEX ix_products_status_created",
    "ALTER TABLE products ADD COLUMN brand_id UUID REFERENCES brands(id) ON DELETE RESTRICT",
    "CREATE INDEX ix_products_brand_id ON products (brand_id)",
    "ALTER TABLE products ADD COLUMN purchase_limit_quantity INTEGER NOT NULL",
    "ALTER TABLE products ADD CONSTRAINT ck_products_purchase_limit CHECK (purchase_limit_quantity >= 0)",
    "CREATE INDEX ix_products_category_status ON products (category_id, status, id)",
    "ALTER TABLE product_skus DROP CONSTRAINT uq_product_sku_specifications",
    "ALTER TABLE product_skus DROP CONSTRAINT ck_product_skus_price",
    "ALTER TABLE product_skus ADD COLUMN sku_no INTEGER NOT NULL",
    "ALTER TABLE product_skus ADD COLUMN specification_key VARCHAR(1000) NOT NULL",
    "ALTER TABLE product_skus ADD COLUMN cost_price NUMERIC(15,2)",
    "ALTER TABLE product_skus ADD COLUMN market_price NUMERIC(15,2)",
    "ALTER TABLE product_skus ADD COLUMN wholesale_prices JSONB NOT NULL",
    "ALTER TABLE product_skus ADD COLUMN archived_at TIMESTAMPTZ",
    "ALTER TABLE product_skus ALTER COLUMN weight_grams DROP NOT NULL",
    "ALTER TABLE product_skus ADD CONSTRAINT uq_product_sku_owner UNIQUE (id,product_id)",
    "ALTER TABLE product_skus ADD CONSTRAINT ck_product_skus_price CHECK (price >= 0 AND price < 'Infinity'::numeric)",
    "ALTER TABLE product_skus ADD CONSTRAINT ck_product_skus_cost CHECK (cost_price >= 0 AND cost_price < 'Infinity'::numeric)",
    "ALTER TABLE product_skus ADD CONSTRAINT ck_product_skus_market CHECK (market_price >= 0 AND market_price < 'Infinity'::numeric)",
    "ALTER TABLE product_skus ADD CONSTRAINT ck_product_skus_number CHECK (sku_no >= 0)",
    "ALTER TABLE product_skus ADD CONSTRAINT ck_product_skus_wholesale CHECK (jsonb_typeof(wholesale_prices) = 'array')",
    "CREATE UNIQUE INDEX uq_product_sku_current_number ON product_skus(product_id,sku_no) WHERE archived_at IS NULL",
    "CREATE UNIQUE INDEX uq_product_sku_current_key ON product_skus(product_id,specification_key) WHERE archived_at IS NULL",
    "CREATE INDEX ix_product_images_asset ON product_images(asset_id)",
    "ALTER TABLE inventory_movements ALTER COLUMN actor_id DROP NOT NULL",
    "ALTER TABLE inventory_movements ADD COLUMN actor_type VARCHAR(16) NOT NULL",
    "ALTER TABLE inventory_movements ADD COLUMN source_type VARCHAR(32) NOT NULL",
    "ALTER TABLE inventory_movements ADD COLUMN source_id UUID",
    "ALTER TABLE inventory_movements ADD COLUMN request_hash VARCHAR(64) NOT NULL",
    "ALTER TABLE inventory_movements ADD CONSTRAINT ck_inventory_movement_revision CHECK (expected_revision > 0 AND resulting_revision = expected_revision + 1)",
    "ALTER TABLE inventory_movements ADD CONSTRAINT ck_inventory_movement_actor CHECK ((actor_type = 'admin' AND actor_id IS NOT NULL) OR (actor_type = 'system' AND actor_id IS NULL AND source_id IS NOT NULL))",
    "ALTER TABLE inventory_movements ADD CONSTRAINT ck_inventory_movement_source CHECK (source_type IN ('manual_adjustment','sku_archive','refund_unshipped'))",
    "ALTER TABLE inventory_movements ADD CONSTRAINT ck_inventory_movement_hash CHECK (length(request_hash) = 64)",
    "COMMENT ON COLUMN products.brand_id IS '可选品牌'",
    "COMMENT ON COLUMN products.purchase_limit_quantity IS '每用户跨 SKU 累计限购，零为不限'",
    "COMMENT ON COLUMN product_skus.sku_no IS '商品内序号，无规格固定为零'",
    "COMMENT ON COLUMN product_skus.specification_key IS '由采用关系生成的稳定规格组合键'",
    "COMMENT ON COLUMN product_skus.cost_price IS '仅管理端可见的成本价'",
    "COMMENT ON COLUMN product_skus.market_price IS '展示市场参考价'",
    "COMMENT ON COLUMN product_skus.wholesale_prices IS '批发阶梯，金额用十进制字符串'",
    "COMMENT ON COLUMN product_skus.archived_at IS '规格转换归档时间，不重新启用'",
    "COMMENT ON COLUMN product_skus.weight_grams IS '选填物流克重，不参与运费'",
    "COMMENT ON COLUMN inventory_movements.actor_id IS '管理员 ID，系统为空'",
    "COMMENT ON COLUMN inventory_movements.actor_type IS '管理员或系统主体'",
    "COMMENT ON COLUMN inventory_movements.source_type IS '人工调整、规格归档或售后回补'",
    "COMMENT ON COLUMN inventory_movements.source_id IS '系统变动来源 ID'",
    "COMMENT ON COLUMN inventory_movements.request_hash IS '规范化请求摘要'",
    "CREATE TABLE spec_attributes (\n\tcode VARCHAR(64) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tvalue_type VARCHAR(16) NOT NULL, \n\tunit VARCHAR(32), \n\tvalidation JSONB NOT NULL, \n\trevision INTEGER NOT NULL, \n\tsort_order INTEGER, \n\tis_active BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_spec_attribute_type CHECK (value_type IN ('text','number','select','multi_select')), \n\tCONSTRAINT ck_spec_attribute_unit CHECK (unit IS NULL OR value_type = 'number'), \n\tCONSTRAINT ck_spec_attribute_validation CHECK (jsonb_typeof(validation) = 'object'), \n\tCONSTRAINT ck_spec_attribute_identity CHECK (revision > 0 AND length(btrim(name)) > 0 AND length(btrim(code)) > 0), \n\tCONSTRAINT ck_spec_attribute_sort CHECK (sort_order >= 0), \n\tUNIQUE (code)\n)",
    "CREATE INDEX ix_spec_attributes_active_sort ON spec_attributes (is_active, sort_order, id)",
    "COMMENT ON TABLE spec_attributes IS '公共销售及描述属性定义'",
    "COMMENT ON COLUMN spec_attributes.code IS '公共属性唯一编码'",
    "COMMENT ON COLUMN spec_attributes.name IS '属性名称'",
    "COMMENT ON COLUMN spec_attributes.value_type IS 'text/number/select/multi_select'",
    "COMMENT ON COLUMN spec_attributes.unit IS '数值单位'",
    "COMMENT ON COLUMN spec_attributes.validation IS '版本化类型验证对象'",
    "COMMENT ON COLUMN spec_attributes.revision IS '公共属性版本'",
    "COMMENT ON COLUMN spec_attributes.sort_order IS '排序权重，值越小越靠前，NULL 表示未人工设置自动排最后'",
    "COMMENT ON COLUMN spec_attributes.is_active IS '启用状态'",
    "CREATE TABLE category_spec_attributes (\n\tcategory_id UUID NOT NULL, \n\tattribute_id UUID NOT NULL, \n\tis_variant BOOLEAN NOT NULL, \n\tis_required BOOLEAN NOT NULL, \n\tsort_order INTEGER, \n\tallow_custom_value BOOLEAN NOT NULL, \n\tPRIMARY KEY (category_id, attribute_id), \n\tCONSTRAINT ck_category_spec_sort CHECK (sort_order >= 0), \n\tFOREIGN KEY(category_id) REFERENCES product_categories (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(attribute_id) REFERENCES spec_attributes (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_category_spec_attributes_attribute_id ON category_spec_attributes (attribute_id)",
    "COMMENT ON TABLE category_spec_attributes IS '分类直接绑定属性模板，不继承父模板'",
    "COMMENT ON COLUMN category_spec_attributes.category_id IS '分类'",
    "COMMENT ON COLUMN category_spec_attributes.attribute_id IS '公共属性'",
    "COMMENT ON COLUMN category_spec_attributes.is_variant IS '是否销售规格'",
    "COMMENT ON COLUMN category_spec_attributes.is_required IS '是否必填'",
    "COMMENT ON COLUMN category_spec_attributes.sort_order IS '排序权重，值越小越靠前，NULL 表示未人工设置自动排最后'",
    "COMMENT ON COLUMN category_spec_attributes.allow_custom_value IS '是否允许局部销售候选值'",
    "CREATE TABLE spec_attribute_values (\n\tattribute_id UUID NOT NULL, \n\tcode VARCHAR(64) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\trevision INTEGER NOT NULL, \n\tsort_order INTEGER, \n\tis_active BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_spec_value_code UNIQUE (attribute_id, code), \n\tCONSTRAINT uq_spec_value_owner UNIQUE (id, attribute_id), \n\tCONSTRAINT ck_spec_value_identity CHECK (revision > 0 AND length(btrim(name)) > 0 AND length(btrim(code)) > 0), \n\tCONSTRAINT ck_spec_value_sort CHECK (sort_order >= 0), \n\tFOREIGN KEY(attribute_id) REFERENCES spec_attributes (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_spec_values_attribute_sort ON spec_attribute_values (attribute_id, sort_order, id)",
    "COMMENT ON TABLE spec_attribute_values IS '公共枚举属性候选值'",
    "COMMENT ON COLUMN spec_attribute_values.attribute_id IS '所属公共属性'",
    "COMMENT ON COLUMN spec_attribute_values.code IS '属性内唯一编码'",
    "COMMENT ON COLUMN spec_attribute_values.name IS '候选值名称'",
    "COMMENT ON COLUMN spec_attribute_values.revision IS '候选值版本，同时递增属性版本'",
    "COMMENT ON COLUMN spec_attribute_values.sort_order IS '排序权重，值越小越靠前，NULL 表示未人工设置自动排最后'",
    "COMMENT ON COLUMN spec_attribute_values.is_active IS '启用状态'",
    "CREATE TABLE product_spec_attributes (\n\tproduct_id UUID NOT NULL, \n\tattribute_id UUID, \n\tadoption_version INTEGER NOT NULL, \n\tname_snapshot VARCHAR(100) NOT NULL, \n\tvalue_type_snapshot VARCHAR(16) NOT NULL, \n\tunit_snapshot VARCHAR(32), \n\tvalidation_snapshot JSONB NOT NULL, \n\tsource_category_id UUID, \n\tsource_category_revision INTEGER, \n\tsource_attribute_revision INTEGER, \n\tis_required BOOLEAN NOT NULL, \n\tallow_custom_value BOOLEAN NOT NULL, \n\tis_variant BOOLEAN NOT NULL, \n\tis_current BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_product_adoption_owner UNIQUE (id, product_id), \n\tCONSTRAINT ck_product_adoption_version CHECK (adoption_version > 0 AND length(btrim(name_snapshot)) > 0), \n\tCONSTRAINT ck_product_adoption_type CHECK (value_type_snapshot IN ('text','number','select','multi_select')), \n\tCONSTRAINT ck_product_adoption_variant CHECK (NOT is_variant OR value_type_snapshot = 'select'), \n\tCONSTRAINT ck_product_adoption_unit CHECK (unit_snapshot IS NULL OR value_type_snapshot = 'number'), \n\tCONSTRAINT ck_product_adoption_validation CHECK (jsonb_typeof(validation_snapshot) = 'object'), \n\tCONSTRAINT ck_product_adoption_category_source CHECK ((source_category_id IS NULL AND source_category_revision IS NULL) OR (source_category_id IS NOT NULL AND source_category_revision IS NOT NULL AND source_category_revision > 0)), \n\tCONSTRAINT ck_product_adoption_source CHECK ((attribute_id IS NULL AND source_attribute_revision IS NULL AND source_category_id IS NULL) OR (attribute_id IS NOT NULL AND source_attribute_revision IS NOT NULL AND source_attribute_revision > 0)), \n\tFOREIGN KEY(product_id) REFERENCES products (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(attribute_id) REFERENCES spec_attributes (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(source_category_id) REFERENCES product_categories (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_product_spec_attributes_attribute_id ON product_spec_attributes (attribute_id)",
    "CREATE INDEX ix_product_spec_attributes_product_id ON product_spec_attributes (product_id)",
    "CREATE UNIQUE INDEX uq_product_adoption_current_attribute ON product_spec_attributes (product_id, attribute_id) WHERE is_current AND attribute_id IS NOT NULL",
    "CREATE UNIQUE INDEX uq_product_adoption_current_name ON product_spec_attributes (product_id, name_snapshot) WHERE is_current",
    "CREATE UNIQUE INDEX uq_product_adoption_version ON product_spec_attributes (product_id, attribute_id, adoption_version) WHERE attribute_id IS NOT NULL",
    "COMMENT ON TABLE product_spec_attributes IS '商品属性冻结采用版本，仅当前标记可退出'",
    "COMMENT ON COLUMN product_spec_attributes.product_id IS '所属商品'",
    "COMMENT ON COLUMN product_spec_attributes.attribute_id IS '公共属性，自建时为空'",
    "COMMENT ON COLUMN product_spec_attributes.adoption_version IS '商品采用版本'",
    "COMMENT ON COLUMN product_spec_attributes.name_snapshot IS '采用名称快照'",
    "COMMENT ON COLUMN product_spec_attributes.value_type_snapshot IS '采用类型快照'",
    "COMMENT ON COLUMN product_spec_attributes.unit_snapshot IS '采用单位快照'",
    "COMMENT ON COLUMN product_spec_attributes.validation_snapshot IS '采用验证规则'",
    "COMMENT ON COLUMN product_spec_attributes.source_category_id IS '模板来源分类'",
    "COMMENT ON COLUMN product_spec_attributes.source_category_revision IS '模板来源版本'",
    "COMMENT ON COLUMN product_spec_attributes.source_attribute_revision IS '公共属性来源版本'",
    "COMMENT ON COLUMN product_spec_attributes.is_required IS '冻结必填规则'",
    "COMMENT ON COLUMN product_spec_attributes.allow_custom_value IS '冻结局部候选授权'",
    "COMMENT ON COLUMN product_spec_attributes.is_variant IS '销售规格标记'",
    "COMMENT ON COLUMN product_spec_attributes.is_current IS '是否当前采用'",
    "COMMENT ON COLUMN product_spec_attributes.created_at IS '采用时间'",
    "CREATE TABLE product_attribute_values (\n\tadoption_id UUID NOT NULL, \n\tproduct_id UUID NOT NULL, \n\tattribute_id UUID, \n\tvalue JSONB NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tdisplay_snapshot JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (adoption_id), \n\tCONSTRAINT fk_description_adoption_owner FOREIGN KEY(adoption_id, product_id) REFERENCES product_spec_attributes (id, product_id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_description_schema CHECK (schema_version = 1 AND jsonb_typeof(display_snapshot) = 'object'), \n\tFOREIGN KEY(product_id) REFERENCES products (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(attribute_id) REFERENCES spec_attributes (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_description_product_attribute ON product_attribute_values (product_id, attribute_id)",
    "COMMENT ON TABLE product_attribute_values IS '非销售属性描述值，按采用版本保留'",
    "COMMENT ON COLUMN product_attribute_values.adoption_id IS '采用版本'",
    "COMMENT ON COLUMN product_attribute_values.product_id IS '所属商品'",
    "COMMENT ON COLUMN product_attribute_values.attribute_id IS '公共属性或空'",
    "COMMENT ON COLUMN product_attribute_values.value IS '类型化描述值，数值为十进制字符串'",
    "COMMENT ON COLUMN product_attribute_values.schema_version IS '描述编码版本'",
    "COMMENT ON COLUMN product_attribute_values.display_snapshot IS '枚举显示文本快照'",
    "CREATE TABLE product_spec_values (\n\tadoption_id UUID NOT NULL, \n\tproduct_id UUID NOT NULL, \n\tattribute_id UUID, \n\tvalue_id UUID, \n\tdisplay_value VARCHAR(100) NOT NULL, \n\tnormalized_value VARCHAR(100) NOT NULL, \n\tis_current BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_product_spec_value_owner UNIQUE (id, adoption_id, product_id), \n\tCONSTRAINT fk_product_spec_value_adoption FOREIGN KEY(adoption_id, product_id) REFERENCES product_spec_attributes (id, product_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_product_spec_value_standard FOREIGN KEY(value_id, attribute_id) REFERENCES spec_attribute_values (id, attribute_id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_product_spec_value_standard CHECK (value_id IS NULL OR attribute_id IS NOT NULL), \n\tCONSTRAINT ck_product_spec_value_text CHECK (length(btrim(display_value)) > 0 AND length(btrim(normalized_value)) > 0), \n\tFOREIGN KEY(product_id) REFERENCES products (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(attribute_id) REFERENCES spec_attributes (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_product_spec_values_adoption_id ON product_spec_values (adoption_id)",
    "CREATE UNIQUE INDEX uq_product_spec_value_custom_current ON product_spec_values (adoption_id, normalized_value) WHERE is_current AND value_id IS NULL",
    "CREATE UNIQUE INDEX uq_product_spec_value_standard_current ON product_spec_values (adoption_id, value_id) WHERE is_current AND value_id IS NOT NULL",
    "COMMENT ON TABLE product_spec_values IS '商品采用下的公共或局部候选值，历史保留'",
    "COMMENT ON COLUMN product_spec_values.adoption_id IS '商品采用记录'",
    "COMMENT ON COLUMN product_spec_values.product_id IS '所属商品'",
    "COMMENT ON COLUMN product_spec_values.attribute_id IS '冗余公共属性身份'",
    "COMMENT ON COLUMN product_spec_values.value_id IS '公共标准值，局部候选为空'",
    "COMMENT ON COLUMN product_spec_values.display_value IS '候选值文本快照'",
    "COMMENT ON COLUMN product_spec_values.normalized_value IS 'NFC 去首尾空白的去重文本'",
    "COMMENT ON COLUMN product_spec_values.is_current IS '是否当前候选'",
    "COMMENT ON COLUMN product_spec_values.created_at IS '创建时间'",
    "CREATE TABLE product_sku_spec_values (\n\tproduct_id UUID NOT NULL, \n\tsku_id UUID NOT NULL, \n\tadoption_id UUID NOT NULL, \n\tattribute_id UUID, \n\tspec_value_id UUID NOT NULL, \n\tPRIMARY KEY (sku_id, adoption_id), \n\tCONSTRAINT fk_sku_spec_sku_owner FOREIGN KEY(sku_id, product_id) REFERENCES product_skus (id, product_id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_sku_spec_value_owner FOREIGN KEY(spec_value_id, adoption_id, product_id) REFERENCES product_spec_values (id, adoption_id, product_id) ON DELETE RESTRICT, \n\tFOREIGN KEY(product_id) REFERENCES products (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(adoption_id) REFERENCES product_spec_attributes (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(attribute_id) REFERENCES spec_attributes (id) ON DELETE RESTRICT\n)",
    "CREATE INDEX ix_product_sku_spec_values_adoption_id ON product_sku_spec_values (adoption_id)",
    "CREATE INDEX ix_product_sku_spec_values_spec_value_id ON product_sku_spec_values (spec_value_id)",
    "COMMENT ON TABLE product_sku_spec_values IS 'SKU 每个采用维度恰一值的稳定组合身份'",
    "COMMENT ON COLUMN product_sku_spec_values.product_id IS '所属商品'",
    "COMMENT ON COLUMN product_sku_spec_values.sku_id IS '稳定 SKU'",
    "COMMENT ON COLUMN product_sku_spec_values.adoption_id IS '采用维度'",
    "COMMENT ON COLUMN product_sku_spec_values.attribute_id IS '公共属性或空'",
    "COMMENT ON COLUMN product_sku_spec_values.spec_value_id IS '商品候选值'",
)


def upgrade() -> None:
    for statement in DDL:
        op.execute(statement)


def downgrade() -> None:
    raise RuntimeError("商品采用和库存历史不能破坏性降级；请前向修复或恢复明确的开发库快照")
