"""Align existing commerce column comments without changing business rows."""

from alembic import op

revision = "20260918_01"
down_revision = "20260917_05"
branch_labels = None
depends_on = None

_COMMENTS: tuple[tuple[str, str, str | None, str | None], ...] = (
    ("cart_items", "quantity", None, "购买意向数量"),
    ("cart_items", "revision", None, "购物车条目版本"),
    ("cart_items", "selected", None, "是否勾选"),
    ("cart_items", "sku_id", None, "稳定 SKU"),
    ("cart_items", "user_id", None, "所属用户"),
    ("commission_records", "amount", None, "佣金总额"),
    ("commission_records", "base_amount", None, "不含运费的商品实付基数"),
    ("commission_records", "beneficiary_user_id", None, "佣金受益人"),
    ("commission_records", "frozen_at", None, "可信支付冻结时间"),
    ("commission_records", "level", None, "一级或二级"),
    ("commission_records", "order_id", None, "来源订单"),
    ("commission_records", "rate", None, "冻结时的佣金比例"),
    ("commission_records", "recovered_amount", None, "累计退款追回额"),
    ("commission_records", "recovered_at", None, "全部追回时间"),
    ("commission_records", "settle_after", None, "交付后结算时间"),
    ("commission_records", "settled_at", None, "钱包入账时间"),
    ("commission_records", "source_user_id", None, "付款用户"),
    ("commission_records", "status", None, "冻结、已结算或已追回"),
    ("commission_recoveries", "amount", None, "本次追回金额"),
    ("commission_recoveries", "commission_id", None, "佣金记录"),
    ("commission_recoveries", "refund_request_id", None, "已成功退款申请"),
    ("fulfillment_events", "actor_id", None, "操作者标识"),
    ("fulfillment_events", "actor_type", None, "操作者类型"),
    ("fulfillment_events", "from_status", None, "原状态"),
    ("fulfillment_events", "fulfillment_id", None, "履约单"),
    ("fulfillment_events", "reason", None, "状态原因"),
    ("fulfillment_events", "revision", None, "对应履约版本"),
    ("fulfillment_events", "to_status", None, "目标状态"),
    ("fulfillments", "auto_confirm_at", None, "实物自动确认收货时间"),
    ("fulfillments", "carrier", None, "物流公司"),
    ("fulfillments", "delivered_at", None, "交付完成时间"),
    ("fulfillments", "delivery_reference", None, "虚拟交付引用"),
    ("fulfillments", "order_id", None, "已支付订单"),
    ("fulfillments", "product_type", None, "实物或虚拟"),
    ("fulfillments", "revision", None, "状态版本"),
    ("fulfillments", "shipped_at", None, "发货时间"),
    ("fulfillments", "status", None, "履约状态"),
    ("fulfillments", "tracking_number", None, "物流单号"),
    ("fulfillments", "updated_by_id", None, "最后操作管理员"),
    ("inventory_reservations", "order_id", None, "订单标识"),
    ("inventory_reservations", "quantity", None, "占用数量"),
    ("inventory_reservations", "released_at", None, "释放时间"),
    ("inventory_reservations", "revision", None, "占用版本"),
    ("inventory_reservations", "sku_id", None, "稳定 SKU"),
    ("inventory_reservations", "status", None, "占用、确认或释放"),
    ("member_profiles", "bound_at", None, "推荐关系绑定时间"),
    ("member_profiles", "invitation_code", None, "本人唯一推荐码"),
    ("member_profiles", "inviter_id", None, "首次绑定的推荐人"),
    ("member_profiles", "level_code", None, "当前会员等级"),
    ("member_profiles", "user_id", None, "会员用户"),
    ("order_events", "actor_id", None, "操作者用户 ID"),
    ("order_events", "actor_type", None, "操作者类型"),
    ("order_events", "from_status", None, "原状态，创建为空"),
    ("order_events", "order_id", None, "订单标识"),
    ("order_events", "reason", None, "状态变更原因"),
    ("order_events", "revision", None, "对应订单版本"),
    ("order_events", "to_status", None, "目标状态"),
    ("order_items", "line_amount", None, "成交行金额"),
    ("order_items", "order_id", None, "所属订单"),
    ("order_items", "product_id", None, "原商品标识，不用于读取历史价格"),
    ("order_items", "product_name", None, "成交商品名称"),
    ("order_items", "product_revision", None, "成交商品资料版本"),
    ("order_items", "quantity", None, "成交数量"),
    ("order_items", "sku_code", None, "成交 SKU 编码"),
    ("order_items", "sku_id", None, "原稳定 SKU 标识"),
    ("order_items", "specifications", None, "成交规格"),
    ("order_items", "unit_price", None, "成交单价"),
    ("order_items", "weight_grams", None, "单件重量克数"),
    ("orders", "address_snapshot", None, "收货地址快照"),
    ("orders", "cancel_reason", None, "取消原因"),
    ("orders", "cancelled_at", None, "取消时间"),
    ("orders", "currency", None, "币种"),
    ("orders", "expires_at", None, "待付款截止时间"),
    ("orders", "freight_amount", None, "运费"),
    ("orders", "items_amount", None, "商品金额"),
    ("orders", "paid_at", None, "可信支付确认时间"),
    ("orders", "payment_reference", None, "支付领域提供的唯一确认标识"),
    ("orders", "pricing_version", None, "计价规则版本"),
    ("orders", "product_type", None, "实物或虚拟，禁止混单"),
    ("orders", "quote_fingerprint", None, "成交报价指纹"),
    ("orders", "request_hash", None, "规范化请求摘要"),
    ("orders", "request_id", None, "用户范围幂等请求号"),
    ("orders", "revision", None, "状态版本"),
    ("orders", "shipping_snapshot", None, "分组运费与规则快照"),
    ("orders", "status", None, "订单状态"),
    ("orders", "total_amount", None, "应付金额"),
    ("orders", "user_id", None, "下单用户"),
    ("payment_attempts", "amount", None, "应支付金额"),
    ("payment_attempts", "channel", None, "支付渠道"),
    ("payment_attempts", "channel_transaction_id", None, "渠道交易流水"),
    ("payment_attempts", "confirmed_at", None, "可信确认时间"),
    ("payment_attempts", "currency", None, "币种"),
    ("payment_attempts", "merchant_reference", None, "商户侧支付意图标识"),
    ("payment_attempts", "order_id", None, "待支付订单"),
    ("payment_attempts", "request_hash", None, "规范化支付请求摘要"),
    ("payment_attempts", "request_id", None, "用户支付请求幂等标识"),
    ("payment_attempts", "revision", None, "状态版本"),
    ("payment_attempts", "status", None, "支付意图状态"),
    ("payment_attempts", "unavailable_reason", None, "渠道不可用原因"),
    ("payment_attempts", "user_id", None, "付款用户"),
    ("payment_events", "from_status", None, "原状态"),
    ("payment_events", "payload_hash", None, "已验签载荷摘要"),
    ("payment_events", "payment_attempt_id", None, "支付意图"),
    ("payment_events", "reason", None, "状态原因"),
    ("payment_events", "revision", None, "对应支付意图版本"),
    ("payment_events", "to_status", None, "目标状态"),
    ("product_reviews", "content", None, "评价正文"),
    ("product_reviews", "is_published", None, "是否公开展示"),
    ("product_reviews", "order_item_id", None, "订单明细"),
    ("product_reviews", "product_id", None, "商品标识"),
    ("product_reviews", "published_at", None, "公开时间"),
    ("product_reviews", "rating", None, "星级"),
    ("product_reviews", "user_id", None, "评价用户"),
    ("reconciliation_records", "amount", None, "渠道金额"),
    ("reconciliation_records", "channel", None, "渠道"),
    ("reconciliation_records", "channel_transaction_id", None, "渠道交易流水"),
    ("reconciliation_records", "currency", None, "币种"),
    ("reconciliation_records", "note", None, "差异说明"),
    ("reconciliation_records", "occurred_at", None, "渠道发生时间"),
    ("reconciliation_records", "payment_attempt_id", None, "匹配的支付意图"),
    ("reconciliation_records", "source_hash", None, "账单行摘要"),
    ("reconciliation_records", "source_reference", None, "账单来源或批次引用"),
    ("reconciliation_records", "status", None, "匹配或差异"),
    ("refund_events", "actor_id", None, "操作者标识"),
    ("refund_events", "actor_type", None, "操作者类型"),
    ("refund_events", "from_status", None, "原状态"),
    ("refund_events", "reason", None, "状态原因"),
    ("refund_events", "refund_request_id", None, "退款申请"),
    ("refund_events", "revision", None, "对应退款版本"),
    ("refund_events", "to_status", None, "目标状态"),
    ("refund_items", "amount", None, "退款商品金额"),
    ("refund_items", "order_item_id", None, "订单明细"),
    ("refund_items", "quantity", None, "退款数量"),
    ("refund_items", "refund_request_id", None, "退款申请"),
    ("refund_requests", "amount", None, "退款商品金额"),
    ("refund_requests", "channel_refund_id", None, "渠道退款流水"),
    ("refund_requests", "confirmed_at", None, "渠道退款确认时间"),
    ("refund_requests", "currency", None, "币种"),
    ("refund_requests", "order_id", None, "原订单"),
    ("refund_requests", "reason", None, "用户申请原因"),
    ("refund_requests", "request_hash", None, "规范化退款请求摘要"),
    ("refund_requests", "request_id", None, "退款请求幂等标识"),
    ("refund_requests", "review_note", None, "审核说明"),
    ("refund_requests", "reviewed_at", None, "审核时间"),
    ("refund_requests", "reviewed_by_id", None, "审核管理员"),
    ("refund_requests", "revision", None, "状态版本"),
    ("refund_requests", "status", None, "退款状态"),
    ("refund_requests", "user_id", None, "申请用户"),
    ("wallet_accounts", "available_amount", None, "可用余额"),
    ("wallet_accounts", "debt_amount", None, "退款追佣未清偿欠款"),
    ("wallet_accounts", "frozen_amount", None, "提现冻结余额"),
    ("wallet_accounts", "revision", None, "余额版本"),
    ("wallet_accounts", "user_id", None, "账户所属用户"),
    ("wallet_accounts", "wallet_type", None, "佣金或消费轨道"),
    ("wallet_ledgers", "amount", None, "可用余额变化，正数入账负数扣减"),
    ("wallet_ledgers", "debt_delta", None, "欠款变化"),
    ("wallet_ledgers", "entry_type", None, "资金变动类型"),
    ("wallet_ledgers", "frozen_delta", None, "冻结余额变化"),
    ("wallet_ledgers", "idempotency_key", None, "业务幂等键"),
    ("wallet_ledgers", "reference_id", None, "关联业务标识"),
    ("wallet_ledgers", "reference_type", None, "关联业务类型"),
    ("wallet_ledgers", "wallet_id", None, "钱包账户"),
    ("withdrawal_requests", "amount", None, "申请金额"),
    ("withdrawal_requests", "channel_reference", None, "未来渠道打款流水"),
    ("withdrawal_requests", "confirmed_at", None, "渠道确认时间"),
    ("withdrawal_requests", "currency", None, "币种"),
    ("withdrawal_requests", "destination_reference", None, "脱敏收款目标引用"),
    ("withdrawal_requests", "request_hash", None, "规范化请求摘要"),
    ("withdrawal_requests", "request_id", None, "用户范围幂等请求号"),
    ("withdrawal_requests", "review_note", None, "审核说明"),
    ("withdrawal_requests", "reviewed_at", None, "审核时间"),
    ("withdrawal_requests", "reviewed_by_id", None, "审核管理员"),
    ("withdrawal_requests", "revision", None, "状态版本"),
    ("withdrawal_requests", "status", None, "申请与渠道执行状态"),
    ("withdrawal_requests", "user_id", None, "申请用户"),
    ("withdrawal_requests", "wallet_id", None, "佣金钱包"),
)


def upgrade() -> None:
    for table, column, before, after in _COMMENTS:
        op.alter_column(table, column, comment=after, existing_comment=before)


def downgrade() -> None:
    for table, column, before, after in reversed(_COMMENTS):
        op.alter_column(table, column, comment=before, existing_comment=after)
