import type { AdminInitialState } from "./app";

export default function access(initialState?: AdminInitialState) {
  const admin = initialState?.currentAdmin;
  const has = (permission: string) => Boolean(admin && (admin.is_superuser || admin.permissions.includes(permission)));
  return {
    canCatalog: [
      "products:read",
      "product-categories:read",
      "shipping:read",
      "settings:order-shipping:read",
      "brands:read",
      "spec-attributes:read",
      "inventory:read",
    ].some(has),
    canProducts: has("products:read"),
    canCategories: has("product-categories:read"),
    canBrands: has("brands:read"),
    canSpecAttributes: has("spec-attributes:read"),
    canInventory: has("inventory:read"),
    canShipping: ["shipping:read", "settings:order-shipping:read"].some(has),
    canTrade: ["orders:read", "refunds:read", "payments:read", "reconciliation:read"].some(has),
    canOrders: has("orders:read"),
    canRefunds: has("refunds:read"),
    canMembership: [
      "users:read",
      "members:read",
      "member-levels:read",
      "member-price-rules:read",
      "points:read",
    ].some(has),
    canUsers: has("users:read"),
    canMembers: has("members:read"),
    canMemberLevels: ["member-levels:read", "member-level-conditions:read"].some(has),
    canMemberPrices: has("member-price-rules:read"),
    canPoints: has("points:read"),
    canDistribution: [
      "withdrawals:read",
      "members:read",
      "commissions:read",
      "wallets:read",
      "commission-policies:read",
      "settings:commission-control:read",
    ].some(has),
    canCommissions: has("commissions:read"),
    canFinance: [
      "payments:read",
      "wallets:read",
      "withdrawals:read",
      "reconciliation:read",
    ].some(has),
    canPayments: has("payments:read"),
    canWallets: has("wallets:read"),
    canWithdrawals: has("withdrawals:read"),
    canReconciliation: has("reconciliation:read"),
    canSystemMgmt: [
      "admins:read",
      "roles:read",
      "permissions:read",
      "assets:read",
      "settings:site:read",
      "settings:registration:read",
    ].some(has),
    canAdmins: has("admins:read"),
    canRoles: has("roles:read"),
    canAssets: has("assets:read"),
    canSettings: ["settings:site:read", "settings:registration:read"].some(has),
    canOps: [
      "security:login-events:read",
      "security:audit-events:read",
      "system:request-logs:read",
      "system:overview:read",
    ].some(has),
    canSecurity: [
      "security:login-events:read",
      "security:audit-events:read",
      "system:request-logs:read",
    ].some(has),
    canSystem: has("system:overview:read"),
  };
}
