export default [
  { path: "/login", component: "../features/auth/LoginPage", layout: false },
  { path: "/", redirect: "/welcome" },
  {
    path: "/welcome",
    name: "工作台",
    icon: "HomeOutlined",
    component: "../features/welcome/WelcomePage",
  },
  {
    path: "/catalog",
    name: "商品中心",
    icon: "ShopOutlined",
    access: "canCatalog",
    routes: [
      { path: "/catalog", redirect: "/catalog/products" },
      { path: "/catalog/products", name: "商品管理", component: "../features/catalog/ProductsPage", access: "canProducts" },
      { path: "/catalog/categories", name: "商品分类", component: "../features/catalog/CategoriesPage", access: "canCategories" },
      { path: "/catalog/brands", name: "品牌管理", component: "../features/catalog/BrandsPage", access: "canBrands" },
      { path: "/catalog/spec-attributes", name: "规格属性", component: "../features/catalog/SpecAttributesPage", access: "canSpecAttributes" },
      { path: "/catalog/inventory", name: "库存管理", component: "../features/catalog/InventoryPage", access: "canInventory" },
      { path: "/catalog/shipping", name: "平台运费", component: "../features/catalog/ShippingPage", access: "canShipping" },
    ],
  },
  {
    path: "/trade",
    name: "交易中心",
    icon: "ShoppingCartOutlined",
    access: "canTrade",
    routes: [
      { path: "/trade", redirect: "/trade/orders" },
      { path: "/trade/orders", name: "订单履约", component: "../features/trade/OrdersPage", access: "canOrders" },
      { path: "/trade/refunds", name: "售后退款", component: "../features/trade/RefundsPage", access: "canRefunds" },
    ],
  },
  {
    key: "membership",
    name: "会员中心",
    icon: "UserOutlined",
    access: "canMembership",
    routes: [
      { path: "/membership", redirect: "/membership/users" },
      { path: "/membership/users", name: "用户管理", component: "../features/users/UsersPage", access: "canUsers" },
      { path: "/membership/members", name: "会员档案", component: "../features/membership/MembersPage", access: "canMembers" },
      { path: "/membership/levels", name: "会员等级", component: "../features/membership/MemberLevelsPage", access: "canMemberLevels" },
      { path: "/membership/prices", name: "会员价格", component: "../features/membership/MemberPricesPage", access: "canMemberPrices" },
      { path: "/membership/points", name: "积分管理", component: "../features/membership/PointsPage", access: "canPoints" },
      { path: "/users", redirect: "/membership/users" },
      { path: "/distribution/members", redirect: "/membership/members" },
    ],
  },
  {
    path: "/distribution",
    name: "分销中心",
    icon: "ApartmentOutlined",
    access: "canDistribution",
    routes: [
      { path: "/distribution", redirect: "/distribution/network" },
      { path: "/distribution/network", name: "推荐关系", component: "../features/distribution/ReferralNetworkPage", access: "canReferralNetwork" },
      { path: "/distribution/policies", name: "分销政策", component: "../features/distribution/PoliciesPage", access: "canPolicies" },
      { path: "/distribution/commissions", name: "佣金记录", component: "../features/distribution/CommissionsPage", access: "canCommissions" },
    ],
  },
  {
    key: "finance",
    name: "财务中心",
    icon: "AccountBookOutlined",
    access: "canFinance",
    routes: [
      { path: "/finance", redirect: "/finance/payments" },
      { path: "/finance/payments", name: "支付记录", component: "../features/trade/PaymentsPage", access: "canPayments" },
      { path: "/finance/refund-records", name: "退款记录", component: "../features/trade/RefundExecutionsPage", access: "canRefundRecords" },
      { path: "/finance/wallets", name: "钱包管理", component: "../features/distribution/WalletsPage", access: "canWallets" },
      { path: "/finance/withdrawals", name: "提现管理", component: "../features/distribution/WithdrawalsPage", access: "canWithdrawals" },
      { path: "/finance/reconciliation", name: "资金对账", component: "../features/trade/ReconciliationPage", access: "canReconciliation" },
      { path: "/trade/payments", redirect: "/finance/payments" },
      { path: "/distribution/wallets", redirect: "/finance/wallets" },
      { path: "/distribution/withdrawals", redirect: "/finance/withdrawals" },
      { path: "/trade/reconciliation", redirect: "/finance/reconciliation" },
    ],
  },
  {
    key: "system-mgmt",
    name: "系统管理",
    icon: "SettingOutlined",
    access: "canSystemMgmt",
    routes: [
      { path: "/system-mgmt", redirect: "/admins" },
      { path: "/admins", name: "管理员", component: "../features/admins/AdminsPage", access: "canAdmins" },
      { path: "/roles", name: "角色权限", component: "../features/roles/RolesPage", access: "canRoles" },
      { path: "/assets", name: "文件资产", component: "../features/assets/AssetsPage", access: "canAssets" },
      { path: "/settings", name: "基础设置", component: "../features/settings/SettingsPage", access: "canSettings" },
    ],
  },
  {
    key: "ops",
    name: "安全运维",
    icon: "SafetyCertificateOutlined",
    access: "canOps",
    routes: [
      { path: "/ops", redirect: "/security" },
      { path: "/security", name: "安全日志", component: "../features/security/SecurityPage", access: "canSecurity" },
      { path: "/system", name: "系统状态", component: "../features/system/SystemStatusPage", access: "canSystem" },
      { path: "/ops/durable-tasks", name: "异步任务", component: "../features/system/DurableTasksPage", access: "canDurableTasks" },
    ],
  },
  { path: "/account/settings", name: "个人设置", component: "../features/account/AccountSettingsPage", hideInMenu: true },
  { path: "*", redirect: "/welcome" },
];
