export default [
  { path: "/login", component: "../features/auth/LoginPage", layout: false },
  { path: "/", redirect: "/welcome" },
  { path: "/welcome", name: "欢迎", icon: "HomeOutlined", component: "../features/welcome/WelcomePage" },
  { path: "/catalog", name: "商品中心", icon: "ShopOutlined", access: "canCatalog", routes: [
    { path: "/catalog", redirect: "/catalog/products" },
    { path: "/catalog/products", name: "商品管理", component: "../features/catalog/ProductsPage", access: "canProducts" },
    { path: "/catalog/categories", name: "商品分类", component: "../features/catalog/CategoriesPage", access: "canCategories" },
    { path: "/catalog/shipping", name: "运费模板", component: "../features/catalog/ShippingPage", access: "canShipping" },
  ] },
  { path: "/trade", name: "交易中心", icon: "ShoppingCartOutlined", access: "canTrade", routes: [
    { path: "/trade", redirect: "/trade/orders" },
    { path: "/trade/orders", name: "订单履约", component: "../features/trade/OrdersPage", access: "canOrders" },
    { path: "/trade/refunds", name: "退款审核", component: "../features/trade/RefundsPage", access: "canRefunds" },
    { path: "/trade/payments", name: "支付记录", component: "../features/trade/PaymentsPage", access: "canPayments" },
    { path: "/trade/reconciliation", name: "支付对账", component: "../features/trade/ReconciliationPage", access: "canReconciliation" },
  ] },
  { path: "/distribution", name: "分销财务", icon: "AccountBookOutlined", access: "canDistribution", routes: [
    { path: "/distribution", redirect: "/distribution/withdrawals" },
    { path: "/distribution/withdrawals", name: "提现审核", component: "../features/distribution/WithdrawalsPage", access: "canWithdrawals" },
    { path: "/distribution/members", name: "会员与推荐关系", component: "../features/distribution/MembersPage", access: "canMembers" },
    { path: "/distribution/commissions", name: "佣金记录", component: "../features/distribution/CommissionsPage", access: "canCommissions" },
    { path: "/distribution/wallets", name: "双轨钱包", component: "../features/distribution/WalletsPage", access: "canWallets" },
  ] },
  { path: "/users", name: "用户", icon: "UserOutlined", component: "../features/users/UsersPage", access: "canUsers" },
  { path: "/admins", name: "管理员", icon: "TeamOutlined", component: "../features/admins/AdminsPage", access: "canAdmins" },
  { path: "/roles", name: "角色权限", icon: "SafetyCertificateOutlined", component: "../features/roles/RolesPage", access: "canRoles" },
  { path: "/assets", name: "文件资产", icon: "FolderOpenOutlined", component: "../features/assets/AssetsPage", access: "canAssets" },
  { path: "/settings", name: "系统设置", icon: "SettingOutlined", component: "../features/settings/SettingsPage", access: "canSettings" },
  { path: "/security", name: "安全日志", icon: "AuditOutlined", component: "../features/security/SecurityPage", access: "canSecurity" },
  { path: "/system", name: "系统状态", icon: "DashboardOutlined", component: "../features/system/SystemStatusPage", access: "canSystem" },
  { path: "/account/settings", name: "个人设置", component: "../features/account/AccountSettingsPage", hideInMenu: true },
  { path: "*", redirect: "/welcome" },
];
