import { http, HttpResponse } from "msw";

const now = "2026-08-15T00:00:00Z";
const admin = {
  id: "01900000-0000-7000-8000-000000000001",
  username: "stage-admin",
  display_name: "Stage Admin",
  is_active: true,
  is_superuser: true,
  roles: [],
  permissions: [],
  created_at: now,
  updated_at: now,
};
const user = {
  id: "01900000-0000-7000-8000-000000000002",
  username: "browser-user",
  display_name: "Browser User",
  email: "browser@example.test",
  avatar: null,
  is_active: true,
  created_at: now,
  updated_at: now,
  deleted_at: null,
  deleted_by_id: null,
  deleted_by_type: null,
  deletion_reason: null,
  can_restore: false,
};
const role = {
  id: "01900000-0000-7000-8000-000000000003",
  code: "operators",
  name: "运营人员",
  description: "日常运营角色",
  is_active: true,
  permissions: ["users:read"],
  created_at: now,
  updated_at: now,
};
const asset = {
  id: "01900000-0000-7000-8000-000000000008",
  uploader_type: "admin",
  uploader_id: admin.id,
  storage_driver: "local",
  file_key: "product/catalog-cover.png",
  original_name: "catalog-cover.png",
  mime_type: "image/png",
  file_size: 2048,
  file_hash: "a".repeat(64),
  url: "/static/uploads/product/catalog-cover.png",
  scene: "product",
  created_at: now,
  updated_at: now,
};
const siteSetting = {
  name: "品界",
  logo: null,
  title: "品界网络科技",
  keywords: ["品界", "网络科技"],
  description: "可靠的数字产品与服务",
  revision: 1,
  updated_at: now,
  updated_by: null,
};

const ok = <T>(data: T) => HttpResponse.json({ code: "OK", message: "操作成功", data, request_id: "test-request" });

export const handlers = [
  http.get("http://localhost:3000/api/v1/system/status", () =>
    HttpResponse.json({ code: "OK", message: "操作成功", data: { status: "available" }, request_id: "test-request" }),
  ),
  http.get("http://localhost:18168/api/v1/system/status", () =>
    HttpResponse.json({ code: "OK", message: "操作成功", data: { status: "available" }, request_id: "test-request" }),
  ),
  http.get("http://localhost:3001/api/v1/system/status", () =>
    HttpResponse.json({ code: "OK", message: "操作成功", data: { status: "available" }, request_id: "test-request" }),
  ),
  http.get("http://localhost:3000/api/v1/admin/auth/me", () => ok(admin)),
  http.get("http://localhost:3000/api/v1/admin/settings/site", () => ok(siteSetting)),
  http.patch("http://localhost:3000/api/v1/admin/settings/site", () => ok({ ...siteSetting, revision: 2 })),
  http.put("http://localhost:3000/api/v1/admin/settings/site/logo", () => ok({ ...siteSetting, revision: 2, logo: { url: "/static/settings/site/logo.png?v=2", mime_type: "image/png", file_size: 128 } })),
  http.delete("http://localhost:3000/api/v1/admin/settings/site/logo", () => ok({ ...siteSetting, revision: 2 })),
  http.get("http://localhost:3000/api/v1/admin/settings/registration", () => ok({ enabled: false, revision: 1, updated_at: now, updated_by: null })),
  http.patch("http://localhost:3000/api/v1/admin/settings/registration", () => ok({ enabled: true, revision: 2, updated_at: now, updated_by: null })),
  http.post("http://localhost:3000/api/v1/admin/auth/login", () => ok({ principal: admin, session_id: admin.id, access_expires_at: now, idle_expires_at: now, absolute_expires_at: now })),
  http.post("http://localhost:3000/api/v1/admin/auth/logout", () => ok({ completed: true })),
  http.post("http://localhost:3000/api/v1/admin/auth/password", () => ok({ completed: true })),
  http.get("http://localhost:3000/api/v1/admin/users", () => ok({ items: [user], page: 1, page_size: 20, total: 1, total_pages: 1 })),
  http.post("http://localhost:3000/api/v1/admin/users", () => ok(user)),
  http.patch("http://localhost:3000/api/v1/admin/users/status/batch", () => ok({ completed_count: 1, target_ids: [user.id] })),
  http.delete("http://localhost:3000/api/v1/admin/users/batch", () => ok({ completed_count: 1, target_ids: [user.id] })),
  http.post("http://localhost:3000/api/v1/admin/users/restore/batch", () => ok({ completed_count: 1, target_ids: [user.id] })),
  http.post("http://localhost:3000/api/v1/admin/users/:id/restore", () => ok({ ...user, is_active: false })),
  http.patch("http://localhost:3000/api/v1/admin/users/:id", () => ok(user)),
  http.patch("http://localhost:3000/api/v1/admin/users/:id/status", () => ok({ ...user, is_active: false })),
  http.put("http://localhost:3000/api/v1/admin/users/:id/credentials/password", () => ok({ completed: true })),
  http.get("http://localhost:3000/api/v1/admin/users/:id/sessions", () =>
    ok({ items: [], page: 1, page_size: 20, total: 0, total_pages: 0 }),
  ),
  http.post("http://localhost:3000/api/v1/admin/users/:id/sessions/revoke-all", () => ok({ completed: true })),
  http.get("http://localhost:3000/api/v1/admin/admins", () => ok({ items: [admin], page: 1, page_size: 20, total: 1, total_pages: 1 })),
  http.post("http://localhost:3000/api/v1/admin/admins", () => ok(admin)),
  http.patch("http://localhost:3000/api/v1/admin/admins/status/batch", () => ok([admin])),
  http.patch("http://localhost:3000/api/v1/admin/admins/:id", () => ok(admin)),
  http.patch("http://localhost:3000/api/v1/admin/admins/:id/superuser", () => ok(admin)),
  http.get("http://localhost:3000/api/v1/admin/admins/:id/sessions", () =>
    ok({ items: [], page: 1, page_size: 20, total: 0, total_pages: 0 }),
  ),
  http.patch("http://localhost:3000/api/v1/admin/admins/:id/status", () => ok(admin)),
  http.put("http://localhost:3000/api/v1/admin/admins/:id/credentials/password", () => ok({ completed: true })),
  http.put("http://localhost:3000/api/v1/admin/admins/:id/roles", () => ok(admin)),
  http.post("http://localhost:3000/api/v1/admin/admins/:id/sessions/revoke-all", () => ok({ completed: true })),
  http.get("http://localhost:3000/api/v1/admin/roles", () => ok({ items: [role], page: 1, page_size: 100, total: 1, total_pages: 1 })),
  http.patch("http://localhost:3000/api/v1/admin/roles/status/batch", () => ok({ completed_count: 1, target_ids: [role.id] })),
  http.delete("http://localhost:3000/api/v1/admin/roles/batch", () => ok({ completed_count: 1, target_ids: [role.id] })),
  http.post("http://localhost:3000/api/v1/admin/roles", () => ok(role)),
  http.patch("http://localhost:3000/api/v1/admin/roles/:id", () => ok(role)),
  http.delete("http://localhost:3000/api/v1/admin/roles/:id", () => ok({ completed: true })),
  http.put("http://localhost:3000/api/v1/admin/roles/:id/permissions", () => ok(role)),
  http.get("http://localhost:3000/api/v1/admin/permissions", () => ok([{ id: "01900000-0000-7000-8000-000000000004", code: "users:read", name: "查看用户", description: "查看用户列表", is_active: true, catalog_version: "v1", assignable_to_roles: true }])),
  http.get("http://localhost:3000/api/v1/assets", () => ok({ items: [asset], page: 1, page_size: 20, total: 1, total_pages: 1 })),
  http.delete("http://localhost:3000/api/v1/assets/batch", () => ok({ completed_count: 1, target_ids: [asset.id] })),
  http.delete("http://localhost:3000/api/v1/assets/:id", () => ok(true)),
  http.get("http://localhost:3000/api/v1/admin/security/login-events", () => ok({ items: [{ id: "01900000-0000-7000-8000-000000000005", principal_type: "admin", principal_id: admin.id, event_type: "login", succeeded: true, reason_code: "success", ip_address: "127.0.0.1", user_agent_summary: "test", request_id: "test-request", occurred_at: now }], page: 1, page_size: 20, total: 1, total_pages: 1 })),
  http.get("http://localhost:3000/api/v1/admin/security/audit-events", () => ok({ items: [{ id: "01900000-0000-7000-8000-000000000006", actor_id: admin.id, action: "users:update", target_type: "user", target_id: user.id, result: "succeeded", changed_fields: {}, request_id: "test-request", occurred_at: now, completed_at: now }], page: 1, page_size: 20, total: 1, total_pages: 1 })),
  http.get("http://localhost:3000/api/v1/admin/system/request-logs", () => ok({ items: [{ id: "01900000-0000-7000-8000-000000000007", request_id: "test-request", trace_id: "test-trace", method: "GET", route_template: "/api/v1/users/me", status_code: 200, duration_ms: 8, principal_type: "user", release_version: "test", occurred_at: now }], page: 1, page_size: 20, total: 1, total_pages: 1 })),
];
